🚚 Update weblate merge-resovling script (#6163)
Currently, the merge-weblate-resolving-conflicts script executes a `doit run _autopr` which generates code and then immediately does a `git commit`. If a new language is added though, some of the newly generated files remain untracked and are not included in the commit. This causes the following merge command to fail:

```
+ git merge -s recursive -X ours origin/main --no-edit
error: The following untracked working tree files would be overwritten by merge:
	grammars/keywords-jbo.lark
Please move or remove them before you merge.
```

Evaluate whether adding a `git add .` before the commit would have unwanted side effects.